<?php

namespace Database\Factories;

use App\Models\Skill;
use Illuminate\Database\Eloquent\Factories\Factory;

class SkillFactory extends Factory
{
    protected $model = Skill::class;

    public function definition()
    {
    
            $skills = [
                'Public Speaking',
                'Communication',
                'Leadership',
                'Time Management',
                'Problem Solving',
                'Teamwork',
                'Critical Thinking',
                'Creativity',
                'Adaptability',
                'Emotional Intelligence',
                'Negotiation',
                'Conflict Resolution',
                'Decision Making',
                'Collaboration',
                'Project Management',
                'Customer Service',
                'Technical Writing',
                'Data Analysis',
                'Research',
                'Attention to Detail',
                'Marketing Strategy',
                'SEO',
                'Social Media Management',
                'Sales',
                'Budgeting',
                'Financial Analysis',
                'Accounting',
                'Programming',
                'Web Development',
                'Mobile Development',
                'Software Testing',
                'Cybersecurity',
                'Cloud Computing',
                'Database Management',
                'Networking',
                'Machine Learning',
                'Artificial Intelligence',
                'Graphic Design',
                'UX/UI Design',
                'Video Editing',
                'Photography',
                'Animation',
                'Copywriting',
                'Content Creation',
                'Email Marketing',
                'Advertising',
                'Branding',
                'Human Resources',
                'Recruitment',
                'Training & Development',
                'Employee Relations',
                'Performance Management',
                'Supply Chain Management',
                'Logistics',
                'Operations Management',
                'Product Management',
                'Business Analysis',
                'Strategic Planning',
                'Risk Management',
                'Quality Assurance',
                'Legal Compliance',
                'Environmental Awareness',
                'Sustainability',
                'Event Planning',
                'Public Relations',
                'Media Relations',
                'Journalism',
                'Teaching',
                'Mentoring',
                'Coaching',
                'Facilitation',
                'Health & Safety',
                'First Aid',
                'CPR',
                'Nutrition',
                'Fitness Training',
                'Yoga',
                'Mindfulness',
                'Stress Management',
                'Counseling',
                'Social Work',
                'Childcare',
                'Elder Care',
                'Pet Care',
                'Housekeeping',
                'Cooking',
                'Baking',
                'Gardening',
                'Home Repair',
                'DIY',
                'Carpentry',
                'Plumbing',
                'Electrical Work',
                'Auto Repair',
                'Driving',
                'Language Skills',
                'Translation',
                'Publications',
                'Journalism',
                'Research Writing',
                'Proposal Writing',
                'Grant Writing',
                'Editing',
                'Proofreading',
                'Ethical Hacking',
                'Blockchain',
                'Cryptocurrency',
            ];
    
            return [
                'title' => $this->faker->randomElement($skills),
                'created_at' => now(),
                'updated_at' => now(),
            ];
       
    }
}